# Ansible inventory created from ['/home/pouchou/Nextcloud/logiciels/netlab-ospf-jmp/big-ospf/topology.yml', 'package:topology-defaults.yml']
#

af:
  ipv4: true
box: quay.io/frrouting/frr:10.0.1
clab:
  binds:
  - clab_files/R10/daemons:/etc/frr/daemons
  - clab_files/R10/hosts:/etc/hosts
  config_templates:
  - daemons:/etc/frr/daemons
  - hosts:/etc/hosts
  kind: linux
hostname: clab-big_ospf-R10
interfaces:
- ifindex: 1
  ifname: eth1
  ipv4: 10.1.0.61/30
  linkindex: 16
  mtu: 1500
  name: R10 -> R2
  neighbors:
  - ifname: eth5
    ipv4: 10.1.0.62/30
    node: R2
  ospf:
    area: 0.0.0.1
    network_type: point-to-point
    passive: false
  type: p2p
- ifindex: 2
  ifname: eth2
  ipv4: 10.1.0.65/30
  linkindex: 17
  mtu: 1500
  name: R10 -> R11
  neighbors:
  - ifname: eth1
    ipv4: 10.1.0.66/30
    node: R11
  ospf:
    area: 0.0.0.1
    network_type: point-to-point
    passive: false
  type: p2p
loopback:
  ifindex: 0
  ifname: lo
  ipv4: 10.0.0.8/32
  neighbors: []
  ospf:
    area: 0.0.0.1
  type: loopback
  virtual_interface: true
mgmt:
  ifname: eth0
  ipv4: 192.168.121.108
  mac: 08:4f:a9:00:00:08
module:
- ospf
mtu: 1500
ospf:
  af:
    ipv4: true
  area: 0.0.0.1
  router_id: 10.0.0.8
