VAGRANT_COMMAND = ARGV[0]

Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
    libvirt.management_network_address = "192.168.121.0/24"
    libvirt.default_prefix = "ospf_4nodes__"
  end
  vm_name = "a1"
  config.vm.define vm_name do |a1|
    a1.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08:4f:a9:00:00:01"
      domain.qemu_use_session = false
    end
    a1.vm.box = "debian/bookworm64"

    $frr_script = <<-SCRIPT
echo "Setting password for user Vagrant"
echo vagrant:vagrant | chpasswd

echo "Enabling SSH password authentication"
sed -i -e "s#PasswordAuthentication no#PasswordAuthentication yes#" /etc/ssh/sshd_config
service sshd restart
    SCRIPT

    $frr_install_script = <<-SCRIPT
set -e
if which /usr/lib/frr/frrinit.sh; then
  echo "FRR already installed, skipping installation"
else
  export DEBIAN_FRONTEND=noninteractive
  echo "Installing GPG, curl, and iproute2"
  apt-get update -qq >/dev/null
  apt-get install -qq curl gnupg iproute2 >/dev/null
  echo "Installing FRR -- set 'netlab_quick_start' node variable to True to skip this step"
  curl -s https://deb.frrouting.org/frr/keys.asc >/etc/apt/trusted.gpg.d/frr.asc
  FRRVER="frr-stable"
  echo deb https://deb.frrouting.org/frr $(lsb_release -s -c) $FRRVER > /etc/apt/sources.list.d/frr.list
  apt-get update -qq >/dev/null
  apt-get install -qq frr frr-pythontools bridge-utils ethtool >/dev/null
  echo "Installation complete"
fi
    SCRIPT
    a1.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true

    a1.vm.provider :libvirt do |domain|
      domain.cpus = 1
      domain.memory = 1024
    end

    # Run debian-specific provisioning script
    #
    a1.vm.provision :shell, :inline => $frr_script + $frr_install_script 
    a1.vm.provider :libvirt do |domain|
    end

    a1.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.1",
                  :libvirt__tunnel_local_port => "10001",
                  :libvirt__tunnel_ip => "127.1.1.2",
                  :libvirt__tunnel_port => "10001",
                  :libvirt__iface_name => "vgif_a1_1",
                  auto_config: false
    a1.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.1",
                  :libvirt__tunnel_local_port => "10002",
                  :libvirt__tunnel_ip => "127.1.1.3",
                  :libvirt__tunnel_port => "10001",
                  :libvirt__iface_name => "vgif_a1_2",
                  auto_config: false
    a1.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.1",
                  :libvirt__tunnel_local_port => "10003",
                  :libvirt__tunnel_ip => "127.1.1.4",
                  :libvirt__tunnel_port => "10001",
                  :libvirt__iface_name => "vgif_a1_3",
                  auto_config: false

  
  end
  vm_name = "a2"
  config.vm.define vm_name do |a2|
    a2.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08:4f:a9:00:00:02"
      domain.qemu_use_session = false
    end
    a2.vm.box = "debian/bookworm64"
    a2.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true

    a2.vm.provider :libvirt do |domain|
      domain.cpus = 1
      domain.memory = 1024
    end

    # Run debian-specific provisioning script
    #
    a2.vm.provision :shell, :inline => $frr_script + $frr_install_script 
    a2.vm.provider :libvirt do |domain|
    end

    a2.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.2",
                  :libvirt__tunnel_local_port => "10001",
                  :libvirt__tunnel_ip => "127.1.1.1",
                  :libvirt__tunnel_port => "10001",
                  :libvirt__iface_name => "vgif_a2_1",
                  auto_config: false
    a2.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.2",
                  :libvirt__tunnel_local_port => "10002",
                  :libvirt__tunnel_ip => "127.1.1.3",
                  :libvirt__tunnel_port => "10002",
                  :libvirt__iface_name => "vgif_a2_2",
                  auto_config: false
    a2.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.2",
                  :libvirt__tunnel_local_port => "10003",
                  :libvirt__tunnel_ip => "127.1.1.4",
                  :libvirt__tunnel_port => "10002",
                  :libvirt__iface_name => "vgif_a2_3",
                  auto_config: false

  
  end
  vm_name = "s1"
  config.vm.define vm_name do |s1|
    s1.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08:4f:a9:00:00:03"
      domain.qemu_use_session = false
    end
    s1.vm.box = "debian/bookworm64"
    s1.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true

    s1.vm.provider :libvirt do |domain|
      domain.cpus = 1
      domain.memory = 1024
    end

    # Run debian-specific provisioning script
    #
    s1.vm.provision :shell, :inline => $frr_script + $frr_install_script 
    s1.vm.provider :libvirt do |domain|
    end

    s1.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.3",
                  :libvirt__tunnel_local_port => "10001",
                  :libvirt__tunnel_ip => "127.1.1.1",
                  :libvirt__tunnel_port => "10002",
                  :libvirt__iface_name => "vgif_s1_1",
                  auto_config: false
    s1.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.3",
                  :libvirt__tunnel_local_port => "10002",
                  :libvirt__tunnel_ip => "127.1.1.2",
                  :libvirt__tunnel_port => "10002",
                  :libvirt__iface_name => "vgif_s1_2",
                  auto_config: false
    s1.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.3",
                  :libvirt__tunnel_local_port => "10003",
                  :libvirt__tunnel_ip => "127.1.1.4",
                  :libvirt__tunnel_port => "10003",
                  :libvirt__iface_name => "vgif_s1_3",
                  auto_config: false

  
  end
  vm_name = "s2"
  config.vm.define vm_name do |s2|
    s2.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08:4f:a9:00:00:04"
      domain.qemu_use_session = false
    end
    s2.vm.box = "debian/bookworm64"
    s2.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true

    s2.vm.provider :libvirt do |domain|
      domain.cpus = 1
      domain.memory = 1024
    end

    # Run debian-specific provisioning script
    #
    s2.vm.provision :shell, :inline => $frr_script + $frr_install_script 
    s2.vm.provider :libvirt do |domain|
    end

    s2.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.4",
                  :libvirt__tunnel_local_port => "10001",
                  :libvirt__tunnel_ip => "127.1.1.1",
                  :libvirt__tunnel_port => "10003",
                  :libvirt__iface_name => "vgif_s2_1",
                  auto_config: false
    s2.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.4",
                  :libvirt__tunnel_local_port => "10002",
                  :libvirt__tunnel_ip => "127.1.1.2",
                  :libvirt__tunnel_port => "10003",
                  :libvirt__iface_name => "vgif_s2_2",
                  auto_config: false
    s2.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.4",
                  :libvirt__tunnel_local_port => "10003",
                  :libvirt__tunnel_ip => "127.1.1.3",
                  :libvirt__tunnel_port => "10003",
                  :libvirt__iface_name => "vgif_s2_3",
                  auto_config: false

  
  end
end
