# Ansible inventory created from ['/home/pouchou/Nextcloud/logiciels/netlab-ospf-jmp/ospf-4nodes-frr/topology.yml', 'package:topology-defaults.yml']
#

af:
  ipv4: true
box: quay.io/frrouting/frr:10.0.1
clab:
  binds:
  - clab_files/s2/daemons:/etc/frr/daemons
  - clab_files/s2/hosts:/etc/hosts
  config_templates:
  - daemons:/etc/frr/daemons
  - hosts:/etc/hosts
  kind: linux
hostname: clab-ospf_4nodes_-s2
interfaces:
- ifindex: 1
  ifname: eth1
  ipv4: 10.1.0.10/30
  linkindex: 4
  mtu: 1500
  name: s2 -> a1
  neighbors:
  - ifname: eth4
    ipv4: 10.1.0.9/30
    node: a1
  ospf:
    area: 0.0.0.1
    network_type: point-to-point
    passive: false
  type: p2p
- ifindex: 2
  ifname: eth2
  ipv4: 10.1.0.18/30
  linkindex: 6
  mtu: 1500
  name: s2 -> a2
  neighbors:
  - ifname: eth3
    ipv4: 10.1.0.17/30
    node: a2
  ospf:
    area: 0.0.0.1
    network_type: point-to-point
    passive: false
  type: p2p
- ifindex: 3
  ifname: eth3
  ipv4: 10.1.0.22/30
  linkindex: 7
  mtu: 1500
  name: s2 -> s1
  neighbors:
  - ifname: eth3
    ipv4: 10.1.0.21/30
    node: s1
  ospf:
    area: 0.0.0.1
    network_type: point-to-point
    passive: false
  type: p2p
loopback:
  ifindex: 0
  ifname: lo
  ipv4: 10.0.0.4/32
  neighbors: []
  ospf:
    area: 0.0.0.1
  type: loopback
  virtual_interface: true
mgmt:
  ifname: eth0
  ipv4: 192.168.121.104
  mac: 08:4f:a9:00:00:04
module:
- ospf
mtu: 1500
ospf:
  af:
    ipv4: true
  area: 0.0.0.1
  router_id: 10.0.0.4
