R1 {
  label: "R1 [frr]\n10.0.0.1/32"
  shape: "oval"
  style.font-size: 20
}
R2 {
  label: "R2 [frr]\n10.0.0.2/32"
  shape: "oval"
  style.font-size: 20
}
R3 {
  label: "R3 [frr]\n10.0.0.3/32"
  shape: "oval"
  style.font-size: 20
}
R4 {
  label: "R4 [frr]\n10.0.0.4/32"
  shape: "oval"
  style.font-size: 20
}
R5 {
  label: "R5 [frr]\n10.0.0.5/32"
  shape: "oval"
  style.font-size: 20
}
R6 {
  label: "R6 [frr]\n10.0.0.6/32"
  shape: "oval"
  style.font-size: 20
}
R7 {
  label: "R7 [frr]\n10.0.0.7/32"
  shape: "oval"
  style.font-size: 20
}
R10 {
  label: "R10 [frr]\n10.0.0.8/32"
  shape: "oval"
  style.font-size: 20
}
R11 {
  label: "R11 [frr]\n10.0.0.9/32"
  shape: "oval"
  style.font-size: 20
}
R19 {
  label: "R19 [frr]\n10.0.0.10/32"
  shape: "oval"
  style.font-size: 20
}
R12 {
  label: "R12 [frr]\n10.0.0.11/32"
  shape: "oval"
  style.font-size: 20
}
R13 {
  label: "R13 [frr]\n10.0.0.12/32"
  shape: "oval"
  style.font-size: 20
}
R14 {
  label: "R14 [frr]\n10.0.0.13/32"
  shape: "oval"
  style.font-size: 20
}
R15 {
  label: "R15 [frr]\n10.0.0.14/32"
  shape: "oval"
  style.font-size: 20
}
R16 {
  label: "R16 [frr]\n10.0.0.15/32"
  shape: "oval"
  style.font-size: 20
}
R18 {
  label: "R18 [frr]\n10.0.0.16/32"
  shape: "oval"
  style.font-size: 20
}
R2 -- R14 {
}
R14 -- R13 {
}
R14 -- R12 {
}
R14 -- R1 {
}
R1 -- R14 {
}
R2 -- R3 {
}
R1 -- R2 {
}
R1 -- R3 {
}
R2 -- R4 {
}
R5 -- R4 {
}
R5 -- R4 {
}
R4 -- R6 {
}
R5 -- R7 {
}
R4 -- R6 {
}
R6 -- R7 {
}
R2 -- R10 {
}
R10 -- R11 {
}
R15 -- R18 {
}
R16 -- R18 {
}
R18 -- R3 {
}
R19 -- R11 {
}
R19 -- R4 {
}
