# Ansible inventory created from ['/home/pouchou/Nextcloud/logiciels/netlab-ospf-jmp/ospf-4nodes-frr/topology.yml', 'package:topology-defaults.yml']
#

af:
  ipv4: true
box: quay.io/frrouting/frr:10.0.1
clab:
  binds:
  - clab_files/s1/daemons:/etc/frr/daemons
  - clab_files/s1/hosts:/etc/hosts
  config_templates:
  - daemons:/etc/frr/daemons
  - hosts:/etc/hosts
  kind: linux
hostname: clab-ospf_4nodes_-s1
interfaces:
- ifindex: 1
  ifname: eth1
  ipv4: 10.1.0.6/30
  linkindex: 3
  mtu: 1500
  name: s1 -> a1
  neighbors:
  - ifname: eth3
    ipv4: 10.1.0.5/30
    node: a1
  ospf:
    area: 0.0.0.1
    network_type: point-to-point
    passive: false
  type: p2p
- ifindex: 2
  ifname: eth2
  ipv4: 10.1.0.14/30
  linkindex: 5
  mtu: 1500
  name: s1 -> a2
  neighbors:
  - ifname: eth2
    ipv4: 10.1.0.13/30
    node: a2
  ospf:
    area: 0.0.0.1
    network_type: point-to-point
    passive: false
  type: p2p
- ifindex: 3
  ifname: eth3
  ipv4: 10.1.0.21/30
  linkindex: 7
  mtu: 1500
  name: s1 -> s2
  neighbors:
  - ifname: eth3
    ipv4: 10.1.0.22/30
    node: s2
  ospf:
    area: 0.0.0.1
    network_type: point-to-point
    passive: false
  type: p2p
loopback:
  ifindex: 0
  ifname: lo
  ipv4: 10.0.0.3/32
  neighbors: []
  ospf:
    area: 0.0.0.1
  type: loopback
  virtual_interface: true
mgmt:
  ifname: eth0
  ipv4: 192.168.121.103
  mac: 08:4f:a9:00:00:03
module:
- ospf
mtu: 1500
ospf:
  af:
    ipv4: true
  area: 0.0.0.1
  router_id: 10.0.0.3
