# Ansible inventory created from ['/home/pouchou/Nextcloud/logiciels/netlab-ospf-jmp/ospf-4nodes-frr/topology.yml', 'package:topology-defaults.yml']
#

%YAML 1.1
---
ospf:
  area: 0.0.0.1
  router_id: 10.0.0.3
  af:
    ipv4: true
interfaces:
- ipv4: 10.1.0.6/30
  linkindex: 2
  ospf:
    area: 0.0.0.1
    passive: false
    network_type: point-to-point
  type: p2p
  name: s1 -> a1
  ifindex: 1
  ifname: eth1
  mtu: 1500
  neighbors:
  - ifname: eth2
    node: a1
    ipv4: 10.1.0.5/30
- ipv4: 10.1.0.14/30
  linkindex: 4
  ospf:
    area: 0.0.0.1
    passive: false
    network_type: point-to-point
  type: p2p
  name: s1 -> a2
  ifindex: 2
  ifname: eth2
  mtu: 1500
  neighbors:
  - ifname: eth2
    node: a2
    ipv4: 10.1.0.13/30
- ipv4: 10.1.0.21/30
  linkindex: 6
  type: p2p
  name: s1 -> s2
  ifindex: 3
  ifname: eth3
  mtu: 1500
  neighbors:
  - ifname: eth3
    node: s2
    ipv4: 10.1.0.22/30
  ospf:
    area: 0.0.0.1
    passive: false
    network_type: point-to-point
clab:
  kind: linux
  config_templates:
  - daemons:/etc/frr/daemons
  - hosts:/etc/hosts
  binds:
  - clab_files/s1/daemons:/etc/frr/daemons
  - clab_files/s1/hosts:/etc/hosts
box: quay.io/frrouting/frr:10.0.1
module:
- ospf
mtu: 1500
af:
  ipv4: true
loopback:
  type: loopback
  neighbors: []
  virtual_interface: true
  ifindex: 0
  ifname: lo
  ipv4: 10.0.0.3/32
  ospf:
    area: 0.0.0.1
mgmt:
  ifname: eth0
  ipv4: 192.168.121.103
  mac: 08:4f:a9:00:00:03
hostname: clab-ospf_4nodes_-s1
