# Ansible inventory created from ['/home/pouchou/Nextcloud/logiciels/netlab-ospf-jmp/ospf-vlan/topology.yml', 'package:topology-defaults.yml']
#

%YAML 1.1
---
module:
- vlan
- ospf
interfaces:
- ipv4: 10.1.0.2/30
  type: p2p
  linkindex: 1
  name: s2 -> s1
  ifindex: 1
  ifname: Ethernet1
  clab:
    name: et1
  neighbors:
  - ifname: Ethernet1
    node: s1
    ipv4: 10.1.0.1/30
  ospf:
    area: 0.0.0.0
    passive: false
    network_type: point-to-point
- vlan:
    access: blue_b
    access_id: 100
  type: lan
  linkindex: 4
  bridge: ospf_vlan_4
  ifindex: 2
  ifname: Ethernet2
  clab:
    name: et2
  neighbors:
  - ifname: eth1
    node: h3
    ipv4: 172.16.1.5/24
  name: '[Access VLAN blue_b] s2 -> h3'
- vlan:
    access: blue_b
    access_id: 100
  type: lan
  linkindex: 5
  bridge: ospf_vlan_5
  ifindex: 3
  ifname: Ethernet3
  clab:
    name: et3
  neighbors:
  - ifname: eth1
    node: h4
    ipv4: 172.16.1.6/24
  name: '[Access VLAN blue_b] s2 -> h4'
- ipv4: 172.16.1.2/24
  vlan:
    mode: irb
    name: blue_b
  type: svi
  ifindex: 40000
  ifname: Vlan100
  name: VLAN blue_b (100) -> [h3,h4]
  virtual_interface: true
  neighbors:
  - ifname: eth1
    node: h3
    ipv4: 172.16.1.5/24
  - ifname: eth1
    node: h4
    ipv4: 172.16.1.6/24
  bridge_group: 1
  role: stub
  ospf:
    area: 0.0.0.0
    passive: true
clab:
  kind: ceos
  env:
    INTFTYPE: et
    CLAB_MGMT_VRF: management
box: registry.iutbeziers.fr/ceos:4.33.1F
ospf:
  area: 0.0.0.0
  router_id: 10.0.0.2
  af:
    ipv4: true
af:
  ipv4: true
loopback:
  type: loopback
  neighbors: []
  virtual_interface: true
  ifindex: 0
  ifname: Loopback0
  ipv4: 10.0.0.2/32
  ospf:
    area: 0.0.0.0
mgmt:
  ifname: Management0
  ipv4: 192.168.121.102
  mac: 08:4f:a9:00:00:02
hostname: clab-ospf_vlan-s2
vlans:
  blue_b:
    id: 100
    prefix:
      ipv4: 172.16.1.0/24
      allocation: id_based
    mode: irb
    bridge_group: 1
vlan:
  max_bridge_group: 1
