# Ansible inventory created from ['/home/pouchou/Nextcloud/logiciels/netlab-ospf-jmp/ospf-4nodes-broadcat-frr/topology.yml', 'package:topology-defaults.yml']
#

hosts:
  r1:
    ipv4:
    - 10.0.0.1
    - 172.16.0.1
    loopback:
    - 10.0.0.1
  r2:
    ipv4:
    - 10.0.0.2
    - 172.16.0.2
    loopback:
    - 10.0.0.2
  r3:
    ipv4:
    - 10.0.0.3
    - 172.16.0.3
    loopback:
    - 10.0.0.3
  r4:
    ipv4:
    - 10.0.0.4
    - 172.16.0.4
    loopback:
    - 10.0.0.4
netlab_name: ospf_4nodes_
netlab_provider: clab
paths_collect:
  dirs:
  - /home/pouchou/.pyenv/versions/3.11.3/envs/netlab/lib/python3.11/site-packages/netsim/ansible/tasks/fetch-config
paths_custom:
  dirs:
  - /home/pouchou/Nextcloud/logiciels/netlab-ospf-jmp/ospf-4nodes-broadcat-frr
  - /home/pouchou/.netlab
  - /home/pouchou/.pyenv/versions/3.11.3/envs/netlab/lib/python3.11/site-packages/netsim/extra
  files:
  - '{{ custom_config + ''/'' + inventory_hostname + ''.'' + netlab_device_type +
    ''-'' + node_provider + ''.j2'' }}'
  - '{{ custom_config + ''/'' + inventory_hostname + ''.'' + netlab_device_type +
    ''.j2'' }}'
  - '{{ custom_config + ''/'' + inventory_hostname + ''.j2'' }}'
  - '{{ custom_config + ''/'' + inventory_hostname + ''.cfg'' }}'
  - '{{ custom_config + ''/'' + netlab_device_type + ''-'' + node_provider + ''.j2''
    }}'
  - '{{ custom_config + ''/'' + netlab_device_type + ''.j2'' }}'
  - '{{ custom_config + ''/'' + ansible_network_os + ''-'' + node_provider + ''.j2''
    }}'
  - '{{ custom_config + ''/'' + ansible_network_os + ''.j2'' }}'
  - '{{ custom_config + ''.'' + inventory_hostname + ''.'' + netlab_device_type +
    ''.j2'' }}'
  - '{{ custom_config + ''.'' + inventory_hostname + ''.'' + ansible_network_os +
    ''.j2'' }}'
  - '{{ custom_config + ''.'' + inventory_hostname + ''.j2'' }}'
  - '{{ custom_config + ''.'' + netlab_device_type + ''.j2'' }}'
  - '{{ custom_config + ''.'' + ansible_network_os + ''.j2'' }}'
  - '{{ custom_config }}'
  - '{{ custom_config + ''.j2'' }}'
  tasks:
  - '{{ custom_config }}/deploy-{{ inventory_hostname }}.yml'
  - '{{ custom_config }}/deploy.{{ netlab_device_type }}-{{ node_provider }}.yml'
  - '{{ custom_config }}/deploy.{{ netlab_device_type }}.yml'
  - '{{ custom_config }}/deploy.{{ ansible_network_os }}-{{ node_provider }}.yml'
  - '{{ custom_config }}/deploy.{{ ansible_network_os }}.yml'
  - '{{ custom_config }}/deploy.yml'
paths_deploy:
  dirs:
  - /home/pouchou/.pyenv/versions/3.11.3/envs/netlab/lib/python3.11/site-packages/netsim/ansible/tasks
  files:
  - '{{ netlab_device_type }}/{{ config_module }}-{{ provider|default(netlab_provider)
    }}.yml'
  - '{{ netlab_device_type }}/{{ config_module }}.yml'
  - deploy-config/{{ netlab_device_type }}-{{ provider|default(netlab_provider) }}.yml
  - deploy-config/{{ netlab_device_type }}.yml
  - '{{ ansible_network_os }}/{{ config_module }}-{{ provider|default(netlab_provider)
    }}.yml'
  - '{{ ansible_network_os }}/{{ config_module }}.yml'
  - deploy-config/{{ ansible_network_os }}-{{ provider|default(netlab_provider) }}.yml
  - deploy-config/{{ ansible_network_os }}.yml
  tasks_generic:
  - deploy-config/{{ netlab_device_type }}-{{ node_provider }}.yml
  - deploy-config/{{ netlab_device_type }}.yml
  - deploy-config/{{ ansible_network_os }}-{{ node_provider }}.yml
  - deploy-config/{{ ansible_network_os }}.yml
paths_plugin:
- /home/pouchou/Nextcloud/logiciels/netlab-ospf-jmp/ospf-4nodes-broadcat-frr
- /home/pouchou/.netlab
- /home/pouchou/.pyenv/versions/3.11.3/envs/netlab/lib/python3.11/site-packages/netsim/extra
paths_ready:
  dirs:
  - /home/pouchou/.pyenv/versions/3.11.3/envs/netlab/lib/python3.11/site-packages/netsim/ansible/tasks/readiness-check
  files:
  - '{{netlab_device_type}}-{{provider|default(netlab_provider)}}.yml'
  - '{{netlab_device_type}}.yml'
  - '{{ansible_network_os}}-{{provider|default(netlab_provider)}}.yml'
  - '{{ansible_network_os}}.yml'
paths_t_files:
  files:
  - '{{config_module}}/{{netlab_device_type}}-{{provider|default(netlab_provider)}}.j2'
  - '{{config_module}}/{{netlab_device_type}}.j2'
  - '{{config_module}}.{{netlab_device_type}}.j2'
  - '{{config_module}}/{{ansible_network_os}}-{{provider|default(netlab_provider)}}.j2'
  - '{{config_module}}/{{ansible_network_os}}.j2'
  - '{{config_module}}.{{ansible_network_os}}.j2'
  - '{{netlab_device_type}}/{{config_module}}.j2'
paths_templates:
  dirs:
  - /home/pouchou/.pyenv/versions/3.11.3/envs/netlab/lib/python3.11/site-packages/netsim/ansible/templates
  - /home/pouchou/.pyenv/versions/3.11.3/envs/netlab/lib/python3.11/site-packages/netsim/daemons
paths_validate:
- /home/pouchou/.pyenv/versions/3.11.3/envs/netlab/lib/python3.11/site-packages/netsim/validate
pools:
  l2only: {}
  lan:
    ipv4: 172.16.0.0/16
    prefix: 24
  loopback:
    ipv4: 10.0.0.0/24
    prefix: 32
  mgmt:
    ipv4: 192.168.121.0/24
    mac: 08-4F-A9-00-00-00
    prefix: 24
    start: 100
  p2p:
    ipv4: 10.1.0.0/16
    prefix: 30
  router_id:
    ipv4: 10.0.0.0/24
    prefix: 32
  vrf_loopback:
    ipv4: 10.2.0.0/24
    prefix: 32
