# Ansible inventory created from ['/home/pouchou/Nextcloud/logiciels/netlab-ospf-jmp/topology.yml', 'package:topology-defaults.yml']
#

%YAML 1.1
---
ansible_network_os: frr
ansible_python_interpreter: auto_silent
netlab_initial: always
netlab_linux_packages:
  gnupg: gpg
  curl: curl
  iproute2: bridge
ansible_connection: docker
ansible_user: root
netlab_show_command:
- vtysh
- -c
- show $@
netlab_mgmt_vrf: true
features:
  initial:
    ipv4:
      unnumbered: true
    ipv6:
      lla: true
  bfd: {}
  bgp:
    activate_af: true
    ipv6_lla: true
    rfc8950: true
    local_as: true
    local_as_ibgp: true
    vrf_local_as: true
    import:
    - ospf
    - ripv2
    - isis
    - connected
    - vrf
    community:
      standard:
      - standard
      - large
      large:
      - large
      extended:
      - extended
      2octet:
      - standard
  evpn:
    irb: true
    asymmetrical_irb: true
  gateway:
    protocol:
    - vrrp
    - anycast
  isis:
    import:
    - bgp
    - ripv2
    - ospf
    - connected
    - vrf
    unnumbered:
      ipv4: true
      ipv6: true
      network: true
  lag:
    passive: false
  mpls:
    ldp: true
    vpn:
      ipv4: true
  ospf:
    unnumbered: true
    import:
    - bgp
    - ripv2
    - isis
    - connected
    - vrf
    default: true
    password: true
    priority: true
    timers: true
  ripv2:
    ipv4: true
    ipv6: true
    passive: true
    import:
    - bgp
    - isis
    - ospf
    - connected
    - vrf
  routing:
    policy:
      set:
        locpref: true
        med: true
        weight: true
        prepend: true
        community:
          standard: true
          large: true
          extended: true
          append: true
      match:
      - prefix
      - nexthop
      - aspath
      - community
    prefix: true
    aspath: true
    community:
      expanded: true
    static:
      vrf: true
      inter_vrf: true
  sr: {}
  stp:
    supported_protocols:
    - stp
    enable_per_port: false
  vlan:
    mixed_trunk: true
    model: router
    native_routed: true
    subif_name: '{ifname}.{vlan.access_id}'
    svi_interface_name: vlan{vlan}
  vrf:
    keep_module: true
    ospfv2: true
    ospfv3: true
    ripv2: true
    ripng: true
    bgp: true
    isis: true
  vxlan:
    vtep6: true
