# Ansible inventory created from ['/home/pouchou/Nextcloud/logiciels/netlab-ospf-jmp/big-ospf/topology.yml', 'package:topology-defaults.yml']
#

ansible_connection: docker
ansible_network_os: frr
ansible_python_interpreter: auto_silent
ansible_user: root
features:
  bfd: {}
  bgp:
    activate_af: true
    community:
      2octet:
      - standard
      extended:
      - extended
      large:
      - large
      standard:
      - standard
      - large
    import:
    - ospf
    - ripv2
    - isis
    - connected
    - vrf
    ipv6_lla: true
    local_as: true
    local_as_ibgp: true
    rfc8950: true
    vrf_local_as: true
  evpn:
    asymmetrical_irb: true
    irb: true
  gateway:
    protocol:
    - vrrp
    - anycast
  initial:
    ipv4:
      unnumbered: true
    ipv6:
      lla: true
  isis:
    import:
    - bgp
    - ripv2
    - ospf
    - connected
    - vrf
    unnumbered:
      ipv4: true
      ipv6: true
      network: true
  lag:
    passive: false
  mpls:
    ldp: true
    vpn:
      ipv4: true
  ospf:
    default: true
    import:
    - bgp
    - ripv2
    - isis
    - connected
    - vrf
    password: true
    priority: true
    timers: true
    unnumbered: true
  ripv2:
    import:
    - bgp
    - isis
    - ospf
    - connected
    - vrf
    ipv4: true
    ipv6: true
    passive: true
  routing:
    aspath: true
    community:
      expanded: true
    policy:
      match:
      - prefix
      - nexthop
      - aspath
      - community
      set:
        community:
          append: true
          extended: true
          large: true
          standard: true
        locpref: true
        med: true
        prepend: true
        weight: true
    prefix: true
    static:
      inter_vrf: true
      vrf: true
  sr: {}
  stp:
    enable_per_port: false
    supported_protocols:
    - stp
  vlan:
    mixed_trunk: true
    model: router
    native_routed: true
    subif_name: '{ifname}.{vlan.access_id}'
    svi_interface_name: vlan{vlan}
  vrf:
    bgp: true
    isis: true
    keep_module: true
    ospfv2: true
    ospfv3: true
    ripng: true
    ripv2: true
  vxlan:
    vtep6: true
netlab_initial: always
netlab_linux_packages:
  curl: curl
  gnupg: gpg
  iproute2: bridge
netlab_mgmt_vrf: true
netlab_show_command:
- vtysh
- -c
- show $@
