# Ansible inventory created from ['/home/pouchou/Nextcloud/logiciels/netlab-ospf-jmp/ospf-multiarea-arista/topology.yml', 'package:topology-defaults.yml']
#

af:
  ipv4: true
box: registry.iutbeziers.fr/ceos:4.33.1F
clab:
  env:
    CLAB_MGMT_VRF: management
    INTFTYPE: et
  kind: ceos
hostname: clab-ospf_multiar-r41
interfaces:
- clab:
    name: et1
  ifindex: 1
  ifname: Ethernet1
  ipv4: 10.1.0.14/30
  linkindex: 5
  name: r41 -> r4
  neighbors:
  - ifname: Ethernet2
    ipv4: 10.1.0.13/30
    node: r4
  ospf:
    area: 0.0.0.4
    network_type: point-to-point
    passive: false
  type: p2p
- bridge: ospf_multi_9
  clab:
    name: et2
  ifindex: 2
  ifname: Ethernet2
  ipv4: 172.16.4.8/24
  linkindex: 9
  name: r41 -> linux4
  neighbors:
  - ifname: eth1
    ipv4: 172.16.4.12/24
    node: linux4
  ospf:
    area: 0.0.0.0
    network_type: point-to-point
    passive: true
  role: stub
  type: lan
loopback:
  ifindex: 0
  ifname: Loopback0
  ipv4: 10.0.0.8/32
  neighbors: []
  ospf:
    area: 0.0.0.0
  type: loopback
  virtual_interface: true
mgmt:
  ifname: Management0
  ipv4: 192.168.121.108
  mac: 08:4f:a9:00:00:08
module:
- ospf
ospf:
  af:
    ipv4: true
  area: 0.0.0.0
  router_id: 10.0.0.8
