# Ansible inventory created from ['/home/pouchou/Nextcloud/logiciels/netlab-ospf-jmp/ospf-multiarea-arista/topology.yml', 'package:topology-defaults.yml']
#

af:
  ipv4: true
box: registry.iutbeziers.fr/ceos:4.33.1F
clab:
  env:
    CLAB_MGMT_VRF: management
    INTFTYPE: et
  kind: ceos
hostname: clab-ospf_multiar-r3
interfaces:
- bridge: ospf_multi_1
  clab:
    name: et1
  ifindex: 1
  ifname: Ethernet1
  ipv4: 172.16.0.3/24
  linkindex: 1
  name: LAN routeurs OSPF
  neighbors:
  - ifname: Ethernet1
    ipv4: 172.16.0.1/24
    node: r1
  - ifname: Ethernet1
    ipv4: 172.16.0.2/24
    node: r2
  - ifname: Ethernet1
    ipv4: 172.16.0.4/24
    node: r4
  ospf:
    area: 0.0.0.0
    passive: false
  type: lan
- clab:
    name: et2
  ifindex: 2
  ifname: Ethernet2
  ipv4: 10.1.0.9/30
  linkindex: 4
  name: r3 -> r31
  neighbors:
  - ifname: Ethernet1
    ipv4: 10.1.0.10/30
    node: r31
  ospf:
    area: 0.0.0.3
    network_type: point-to-point
    passive: false
  type: p2p
loopback:
  ifindex: 0
  ifname: Loopback0
  ipv4: 10.0.0.3/32
  neighbors: []
  ospf:
    area: 0.0.0.0
  type: loopback
  virtual_interface: true
mgmt:
  ifname: Management0
  ipv4: 192.168.121.103
  mac: 08:4f:a9:00:00:03
module:
- ospf
ospf:
  af:
    ipv4: true
  area: 0.0.0.0
  router_id: 10.0.0.3
