# Ansible inventory created from ['/home/pouchou/Nextcloud/logiciels/netlab-ospf-jmp/ospf-multiarea-arista/topology.yml', 'package:topology-defaults.yml']
#

af:
  ipv4: true
box: registry.iutbeziers.fr/ceos:4.33.1F
clab:
  env:
    CLAB_MGMT_VRF: management
    INTFTYPE: et
  kind: ceos
hostname: clab-ospf_multiar-r21
interfaces:
- clab:
    name: et1
  ifindex: 1
  ifname: Ethernet1
  ipv4: 10.1.0.6/30
  linkindex: 3
  name: r21 -> r2
  neighbors:
  - ifname: Ethernet2
    ipv4: 10.1.0.5/30
    node: r2
  ospf:
    area: 0.0.0.2
    network_type: point-to-point
    passive: false
  type: p2p
- bridge: ospf_multi_7
  clab:
    name: et2
  ifindex: 2
  ifname: Ethernet2
  ipv4: 172.16.2.6/24
  linkindex: 7
  name: r21 -> linux2
  neighbors:
  - ifname: eth1
    ipv4: 172.16.2.10/24
    node: linux2
  ospf:
    area: 0.0.0.0
    network_type: point-to-point
    passive: true
  role: stub
  type: lan
loopback:
  ifindex: 0
  ifname: Loopback0
  ipv4: 10.0.0.6/32
  neighbors: []
  ospf:
    area: 0.0.0.0
  type: loopback
  virtual_interface: true
mgmt:
  ifname: Management0
  ipv4: 192.168.121.106
  mac: 08:4f:a9:00:00:06
module:
- ospf
ospf:
  af:
    ipv4: true
  area: 0.0.0.0
  router_id: 10.0.0.6
