# Ansible inventory created from ['/home/pouchou/Nextcloud/logiciels/netlab-ospf-jmp/big-ospf/topology.yml', 'package:topology-defaults.yml']
#

af:
  ipv4: true
box: quay.io/frrouting/frr:10.0.1
clab:
  binds:
  - clab_files/R4/daemons:/etc/frr/daemons
  - clab_files/R4/hosts:/etc/hosts
  config_templates:
  - daemons:/etc/frr/daemons
  - hosts:/etc/hosts
  kind: linux
hostname: clab-big_ospf-R4
interfaces:
- ifindex: 1
  ifname: eth1
  ipv4: 10.1.0.34/30
  linkindex: 9
  mtu: 1500
  name: R4 -> R2
  neighbors:
  - ifname: eth4
    ipv4: 10.1.0.33/30
    node: R2
  ospf:
    area: 0.0.0.0
    network_type: point-to-point
    passive: false
  type: p2p
- ifindex: 2
  ifname: eth2
  ipv4: 10.1.0.37/30
  linkindex: 10
  mtu: 1500
  name: R4 -> R5
  neighbors:
  - ifname: eth1
    ipv4: 10.1.0.38/30
    node: R5
  ospf:
    area: 0.0.0.0
    cost: 10000
    network_type: point-to-point
    passive: false
  type: p2p
- ifindex: 3
  ifname: eth3
  ipv4: 10.1.0.41/30
  linkindex: 11
  mtu: 1500
  name: R4 -> R5
  neighbors:
  - ifname: eth2
    ipv4: 10.1.0.42/30
    node: R5
  ospf:
    area: 0.0.0.0
    network_type: point-to-point
    passive: false
  type: p2p
- ifindex: 4
  ifname: eth4
  ipv4: 10.1.0.45/30
  linkindex: 12
  mtu: 1500
  name: R4 -> R6
  neighbors:
  - ifname: eth1
    ipv4: 10.1.0.46/30
    node: R6
  ospf:
    area: 0.0.0.4
    network_type: point-to-point
    passive: false
  type: p2p
- ifindex: 5
  ifname: eth5
  ipv4: 10.1.0.53/30
  linkindex: 14
  mtu: 1500
  name: R4 -> R6
  neighbors:
  - ifname: eth2
    ipv4: 10.1.0.54/30
    node: R6
  ospf:
    area: 0.0.0.4
    network_type: point-to-point
    passive: false
  type: p2p
- ifindex: 6
  ifname: eth6
  ipv4: 10.1.0.86/30
  linkindex: 22
  mtu: 1500
  name: R4 -> R19
  neighbors:
  - ifname: eth2
    ipv4: 10.1.0.85/30
    node: R19
  ospf:
    area: 0.0.0.1
    network_type: point-to-point
    passive: false
  type: p2p
loopback:
  ifindex: 0
  ifname: lo
  ipv4: 10.0.0.4/32
  neighbors: []
  ospf:
    area: 0.0.0.0
  type: loopback
  virtual_interface: true
mgmt:
  ifname: eth0
  ipv4: 192.168.121.104
  mac: 08:4f:a9:00:00:04
module:
- ospf
mtu: 1500
ospf:
  af:
    ipv4: true
  area: 0.0.0.0
  router_id: 10.0.0.4
