# Ansible inventory created from ['/home/pouchou/Nextcloud/logiciels/netlab-ospf-jmp/ospf-multiarea-arista/topology.yml', 'package:topology-defaults.yml']
#

all: {}
custom_configs:
  hosts: {}
daemons:
  hosts: {}
eos:
  hosts:
    r1:
      ansible_host: clab-ospf_multiar-r1
      id: 1
    r11:
      ansible_host: clab-ospf_multiar-r11
      id: 5
    r2:
      ansible_host: clab-ospf_multiar-r2
      id: 2
    r21:
      ansible_host: clab-ospf_multiar-r21
      id: 6
    r3:
      ansible_host: clab-ospf_multiar-r3
      id: 3
    r31:
      ansible_host: clab-ospf_multiar-r31
      id: 7
    r4:
      ansible_host: clab-ospf_multiar-r4
      id: 4
    r41:
      ansible_host: clab-ospf_multiar-r41
      id: 8
linux:
  hosts:
    linux1:
      ansible_host: clab-ospf_multiar-linux1
      id: 9
    linux2:
      ansible_host: clab-ospf_multiar-linux2
      id: 10
    linux3:
      ansible_host: clab-ospf_multiar-linux3
      id: 11
    linux4:
      ansible_host: clab-ospf_multiar-linux4
      id: 12
modules:
  hosts:
    r1: {}
    r11: {}
    r2: {}
    r21: {}
    r3: {}
    r31: {}
    r4: {}
    r41: {}
