# Ansible inventory created from ['/home/pouchou/Nextcloud/logiciels/netlab-ospf-jmp/big-ospf/topology.yml', 'package:topology-defaults.yml']
#

af:
  ipv4: true
box: quay.io/frrouting/frr:10.0.1
clab:
  binds:
  - clab_files/R5/daemons:/etc/frr/daemons
  - clab_files/R5/hosts:/etc/hosts
  config_templates:
  - daemons:/etc/frr/daemons
  - hosts:/etc/hosts
  kind: linux
hostname: clab-big_ospf-R5
interfaces:
- ifindex: 1
  ifname: eth1
  ipv4: 10.1.0.38/30
  linkindex: 10
  mtu: 1500
  name: R5 -> R4
  neighbors:
  - ifname: eth2
    ipv4: 10.1.0.37/30
    node: R4
  ospf:
    area: 0.0.0.3
    cost: 10000
    network_type: point-to-point
    passive: false
  type: p2p
- ifindex: 2
  ifname: eth2
  ipv4: 10.1.0.42/30
  linkindex: 11
  mtu: 1500
  name: R5 -> R4
  neighbors:
  - ifname: eth3
    ipv4: 10.1.0.41/30
    node: R4
  ospf:
    area: 0.0.0.3
    network_type: point-to-point
    passive: false
  type: p2p
- ifindex: 3
  ifname: eth3
  ipv4: 10.1.0.49/30
  linkindex: 13
  mtu: 1500
  name: R5 -> R7
  neighbors:
  - ifname: eth1
    ipv4: 10.1.0.50/30
    node: R7
  ospf:
    area: 0.0.0.4
    network_type: point-to-point
    passive: false
  type: p2p
loopback:
  ifindex: 0
  ifname: lo
  ipv4: 10.0.0.5/32
  neighbors: []
  ospf:
    area: 0.0.0.3
  type: loopback
  virtual_interface: true
mgmt:
  ifname: eth0
  ipv4: 192.168.121.105
  mac: 08:4f:a9:00:00:05
module:
- ospf
mtu: 1500
ospf:
  af:
    ipv4: true
  area: 0.0.0.3
  router_id: 10.0.0.5
