# Ansible inventory created from ['/home/pouchou/Nextcloud/logiciels/netlab-ospf-jmp/ospf-vlan/topology.yml', 'package:topology-defaults.yml']
#

%YAML 1.1
---
interfaces:
- ipv4: 172.16.0.4/24
  type: lan
  linkindex: 3
  bridge: ospf_vlan_3
  name: h2 -> [h1,s1]
  ifindex: 1
  ifname: eth1
  mtu: 1500
  neighbors:
  - ifname: eth1
    node: h1
    ipv4: 172.16.0.3/24
  - ifname: Vlan100
    node: s1
    ipv4: 172.16.0.1/24
  gateway:
    ipv4: 172.16.0.1/24
  role: stub
clab:
  kind: linux
  config_templates:
  - hosts:/etc/hosts
  binds:
  - clab_files/h2/hosts:/etc/hosts
box: python:3.9-alpine
role: host
mtu: 1500
af:
  ipv4: true
mgmt:
  ifname: eth0
  ipv4: 192.168.121.104
  mac: 08:4f:a9:00:00:04
hostname: clab-ospf_vlan-h2
routing:
  static:
  - ipv4: 172.16.0.0/16
    nexthop:
      ipv4: 172.16.0.1
      intf: eth1
      idx: 0
  - ipv4: 10.0.0.0/24
    nexthop:
      ipv4: 172.16.0.1
      intf: eth1
      idx: 0
  - ipv4: 10.1.0.0/16
    nexthop:
      ipv4: 172.16.0.1
      intf: eth1
      idx: 0
  - ipv4: 10.2.0.0/24
    nexthop:
      ipv4: 172.16.0.1
      intf: eth1
      idx: 0
